[background-color="#01303a"]
== Java version support and other JVM languages

=== Combine JVM Plugins

[plantuml, plugins5, png, width=800, height=0%]
....
scale 1600 width
skinparam class {
	ArrowColor Black
}

rectangle "java-library" <<Plugin>> #lightyellow  {
}

rectangle "application" <<Plugin>> #lightyellow {
}

rectangle "java" <<Plugin>> {
}

rectangle "java-base" <<Plugin>> {
}

"java-library" --> java : apply()
application --> java : apply()
java --> "java-base" : apply()

rectangle "groovy" <<Plugin>> #lightgreen  {
}

rectangle "scala" <<Plugin>> #lightgreen {
}

groovy --> java : apply()
scala --> java : apply()
....

=== Support for JDK 13

Use in one project
```kotlin
java {
    sourceCompatibility = JavaVersion.VERSION_13
    targetCompatibility = JavaVersion.VERSION_13
}
```

Or use in all subprojects
```kotlin
subprojects {
    plugins.withType<JavaPlugin> {
        extensions.configure<JavaPluginExtension> {
            sourceCompatibility = JavaVersion.VERSION_13
            targetCompatibility = JavaVersion.VERSION_13
        }
    }
}
```

JDK 14 support will be available in Gradle 6.3 (~March 2020)

=== Enable JDK preview features

Turn on support for Java 13 preview features like _text blocks_
```kotlin
// for compilation
tasks.withType<JavaCompile> {
    options.compilerArgs.add("--enable-preview")
}

// to run tests
tasks.withType<Test>  {
    jvmArgs = listOf("--enable-preview")
}

// to run an application
application {
    applicationDefaultJvmArgs = listOf("--enable-preview")
}
```

```kotlin
// to generate Javadoc
tasks.withType<Javadoc>  {
    val javadocOptions = options as CoreJavadocOptions
    javadocOptions.addStringOption("source", "13")
    javadocOptions.addBooleanOption("-enable-preview", true)
}
```

=== Support for Java Project Module System (JPMS)

- Basic support available through 3rd party plugins right now
- Initial support in Gradle core planned for 6.4 or 6.5 (~April/May 2020)
